services:
  bot:
    build: .
    container_name: yomiage-bot
    restart: always
    depends_on:
      - voicevox
    volumes:
      - ./data:/usr/src/app/data
    env_file:
      - .env

  voicevox:
    image: voicevox/voicevox_engine:cpu-amd64-ubuntu24.04-latest
    container_name: voicevox-engine
    restart: always
    command: ["python", "run.py", "--host", "0.0.0.0", "--cpu_num_threads=4"]
    ports:
      - "50021:50021"
